language: ruby
rvm:
- 2.1

install: gem install bundler
script: bundle install && rm -f ./_site && bundle exec jekyll build && bundle exec htmlproof ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
